version: '3'

services:
  salt-master:
    build:
      context: .
      dockerfile: Dockerfile.master
  salt-minion:
    build:
      context: .
      dockerfile: Dockerfile.minion
    depends_on:
      - salt-master
